name: Build MK Call Reader APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:

      # 1. Download repository
      - name: Checkout Repository
        uses: actions/checkout@v4


      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


      # 3. Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4


      # 4. Build Debug APK
      - name: Build APK
        run: gradle assembleDebug


      # 5. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MK-Call-Reader-APK
          path: app/build/outputs/apk/debug/app-debug.apk
